### ISSUE TITLE
Question marks(???) on detected chords

### ISSUE THREAD

**Issue by SutirthaChakraborty** [jonathangjertsen/jchord#46]
[a.txt](https://github.com/jonathangjertsen/jchord/files/5027830/a.txt)
I uploaded a midi file and tried to recognize the chords. I found that many chords are recognized with '???' which could be minor or major, can you please let me know the problem?

**Comment by jonathangjertsen** [comment]
This means that it couldn't recognize the chord. Can you send the MIDI file in question so I can have a look?

**Comment by SutirthaChakraborty** [comment]
[a.zip](https://github.com/jonathangjertsen/jchord/files/5028455/a.zip)

**Comment by jonathangjertsen** [comment]
Thanks! I'll get back to you on this

**Comment by jonathangjertsen** [comment]
This should be improved in [the latest release](https://github.com/jonathangjertsen/jchord/releases/tag/v0.2.0)

```Python
from jchord.progressions import ChordProgression
print(ChordProgression.from_midi_file("a.mid").to_string())
```

output:

```
Dmin   D      Dmin   D5
D      F#min  F#     D
Bmin   F#min  D      Bmin
F#min  A      D      Emin
B      A      D      A
D      G      A      D
A      D      G      A
D      Bmin   F#min  D
Bmin   F#min  A      D
Bmin   F#     Emin   Gmin
A      D      A      D
G      A      D      A
D      G      A      D
Bmin   F#min  D      Bmin
F#min  A      A5     D
Gmin   Emin   B      A
D      A      D      G
A      D      A      D
G      A      D      Bmin
F#min  D      Bmin   F#min
A      D      F#min  A
D      Bmin   F#min  D
Bmin   F#min  A      D
A      D      F#     Emin
B      A      D
```

The timing information in the midi file is not used in any way at the moment,
so the default formatting of 4 chords per line doesn't make much sense in this example.
The chords themselves look about right to me though.

**Comment by SutirthaChakraborty** [comment]
Thank you, it's working now.  Cheers
