### ISSUE TITLE
Any function to convert a audio to midi ?

### ISSUE THREAD

**Issue by SutirthaChakraborty** [jonathangjertsen/jchord#50]
Hi ,
Are there any function to :  
1.  Directly convert the audio into midi?
2.  Directly transpose the chord progression of a full midi file ?
 
Thanks, 
Suti

**Comment by jonathangjertsen** [comment]
Hi, thanks for asking. Regarding 1), anything to do with audio is out of scope for this library. The only software I know of that can do pitch detection on chords is Melodyne. As for 2), there is no such function at the moment, but the building blocks are there and it's a good idea. I have added a separate issue that will enable this feature.

**Comment by SutirthaChakraborty** [comment]
Thank you
