### ISSUE TITLE
Root note when using ChordProgression.from_string()

### ISSUE THREAD

**Issue by flexiblestoic** [jonathangjertsen/jchord#61]
Hi, 

Fantastic piece of software. I was wondering if there is a way to define the root note when injecting the chord progression from a string?

Thanks,
Chris

**Comment by jonathangjertsen** [comment]
I'm not sure what you mean - the root note will be derived from the chord names in the string. The octave is chosen arbitrarily though - is that what you want to be able to specify?

Maybe you can provide some example code showing how you would like to use it?

**Comment by flexiblestoic** [comment]
Yes, I was thinking about the octave of the root note. I would use it like:

`prog = ChordProgression.from_string("4F -- 3Am -- 4Dm7 -- 4F --")`

Meaning the roots would be F4 A3 D4 and F4. The octave number before the note would be optional.

**Comment by jonathangjertsen** [comment]
I see! Having the octave in front is a nice solution, I don't think it conflicts with any of the existing notation. It could probably be extended to solve https://github.com/jonathangjertsen/jchord/issues/1 as well. I'll give it a go!

**Comment by flexiblestoic** [comment]
#1 Indeed. So the octave in front wouldn't the best solution to generalize. Maybe an optional dot notation? 
The first inversion of C major starting on E4 would be E4.C 
A C major starting on C5 would be C5.C

**Comment by jonathangjertsen** [comment]
I've added support for the octave in front, available in version 1.0.0 (pip install jchord==1.0.0)

**Comment by jonathangjertsen** [comment]
> The first inversion of C major starting on E4 would be E4.C

If you just need to change the bass note, this is supported with slash chords, in this case you would write "5C/E". The "/E" adds an E below the root

**Comment by flexiblestoic** [comment]
Just tested. Works awesome. Thanks Jonathan!
