### ISSUE TITLE
Arpeggios/string instruments

### ISSUE THREAD

**Issue by flexiblestoic** [jonathangjertsen/jchord#62]
Hi Jonathan,

I was wondering, would it be interesting to have a function that introduces gaps between notes of a chord. That way, one could either make instruments like guitar more realistic, emulating the pick hitting one string after another. Furthermore with longer intervals it could allow arpeggios?

Thanks,
Chris

**Comment by jonathangjertsen** [comment]
Hi Chris, please check out the 2.0.0 release which adds options for adding these kinds of "midi effects" to the exported MIDI file. There is an example file here https://github.com/jonathangjertsen/jchord/blob/v2.0.0/examples/autumn_leaves.py

**Comment by flexiblestoic** [comment]
This is superb. Thanks!. Really helps to 'visualize' those chords. Awesome for people learning and experimenting with chord progressions. 
What is your setting to read midi files? I use VLC with an audio font I found online but I see in your code you can manage several instruments?

**Comment by jonathangjertsen** [comment]
For testing the midi files I usually just play them in Windows Media Player, or open them in Audacity if I need to see the notes. The `instrument` option sets the track's instrument as defined in the General MIDI 1 spec (https://www.midi.org/specifications-old/item/gm-level-1-sound-set), does that answer your question?

**Comment by flexiblestoic** [comment]
Yes, thanks again!
